# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build, with maven

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set version env to use
        run: echo "VER=$(git describe --tags --match v*.*.* | cut -c 2-)" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build spigot
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.19 # --rev
          generateSrc: false # --generate-source
          generateDoc: false # --generate-docs
          disableJavaCheck: false # --disable-java-check
          remapped: true # --remapped
          forceRun: false # Optional
          threads: -1 # Optional
          buildToolProvider: SpigotMC # Optional
      - name: Build project with Maven
        run: mvn --batch-mode -Drevision=${{ env.VER }} package
      - name: Delete remapped-jar
        run: |
          rm target/*remapped*.jar
      - name: Release latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/Fish*.jar
