# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build latest dev
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build_latest:
    name: Build latest
    uses: ./.github/workflows/build.yml
    with:
      autotag: "latest"
      prerelease: true
      title: "Development build"
