# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_latest:
    name: Build release
    uses: ./.github/workflows/build.yml
    with:
      autotag: ""
      prerelease: false
      title: ""
