on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build
        with:
          autotag: "latest"
          prerelease: true
          title: "Development build"
